# Generated by Django 4.2.11 on 2025-09-24 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxpayerSiiCredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tax_id",
                    models.CharField(help_text="RUT del contribuyente", max_length=20),
                ),
                (
                    "encrypted_password",
                    models.TextField(help_text="Contraseña del SII encriptada"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "last_verified",
                    models.DateTimeField(
                        blank=True, help_text="Última verificación exitosa", null=True
                    ),
                ),
                (
                    "verification_failures",
                    models.IntegerField(
                        default=0, help_text="Contador de fallos de verificación"
                    ),
                ),
                (
                    "company",
                    models.OneToOneField(
                        help_text="Empresa asociada a estas credenciales",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxpayer_sii_credentials",
                        to="companies.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Usuario que registró estas credenciales",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Taxpayer SII Credentials",
                "verbose_name_plural": "Taxpayer SII Credentials",
                "db_table": "taxpayer_sii_credentials",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tax_id"], name="taxpayer_si_tax_id_6b47ef_idx"
                    ),
                    models.Index(
                        fields=["company"], name="taxpayer_si_company_5e498f_idx"
                    ),
                    models.Index(
                        fields=["user"], name="taxpayer_si_user_id_be4ec6_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TaxPayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rut", models.CharField(blank=True, default="", max_length=12)),
                ("dv", models.CharField(blank=True, default="", max_length=1)),
                (
                    "tax_id",
                    models.CharField(
                        help_text="RUT con formato completo del SII",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "razon_social",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "data_source",
                    models.CharField(
                        default="sii_extraction",
                        help_text="Origen de los datos",
                        max_length=50,
                    ),
                ),
                (
                    "last_sii_sync",
                    models.DateTimeField(
                        blank=True, help_text="Última sincronización con SII", null=True
                    ),
                ),
                (
                    "sii_raw_data",
                    models.JSONField(
                        blank=True, help_text="Datos completos del SII", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Verificado contra SII"
                    ),
                ),
                (
                    "setting_procesos",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Configuración de procesos tributarios habilitados para este contribuyente",
                    ),
                ),
                (
                    "company",
                    models.OneToOneField(
                        help_text="Empresa a la que pertenece este contribuyente",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxpayer",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "TaxPayer",
                "verbose_name_plural": "TaxPayers",
                "db_table": "taxpayers",
                "ordering": ["razon_social"],
                "indexes": [
                    models.Index(fields=["rut", "dv"], name="taxpayers_rut_0a0e96_idx"),
                    models.Index(fields=["tax_id"], name="taxpayers_tax_id_d9ec61_idx"),
                    models.Index(
                        fields=["razon_social"], name="taxpayers_razon_s_39f5e8_idx"
                    ),
                ],
            },
        ),
    ]
