# Generated by Django 4.2.11 on 2025-08-31 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaxpayerActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("description", models.TextField()),
                ("category", models.CharField(blank=True, max_length=50)),
                ("subcategory", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Taxpayer Activity",
                "verbose_name_plural": "Taxpayer Activities",
                "db_table": "taxpayer_activities",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="TaxpayerStamp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company_rut",
                    models.CharField(
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator("^\\d{7,8}$")
                        ],
                    ),
                ),
                (
                    "company_dv",
                    models.CharField(
                        max_length=1,
                        validators=[django.core.validators.RegexValidator("^[0-9Kk]$")],
                    ),
                ),
                ("stamp_id", models.CharField(max_length=50, unique=True)),
                ("certificate_serial", models.CharField(max_length=100)),
                ("certificate_subject", models.TextField()),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                (
                    "stamp_type",
                    models.CharField(
                        choices=[
                            ("production", "Producción"),
                            ("certification", "Certificación"),
                        ],
                        default="production",
                        max_length=20,
                    ),
                ),
                (
                    "document_types",
                    models.JSONField(
                        default=list, help_text="Tipos de documentos autorizados"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Taxpayer Stamp",
                "verbose_name_plural": "Taxpayer Stamps",
                "db_table": "taxpayer_stamps",
                "ordering": ["company_rut", "-valid_until"],
                "indexes": [
                    models.Index(
                        fields=["company_rut", "company_dv"],
                        name="taxpayer_st_company_3830a3_idx",
                    ),
                    models.Index(
                        fields=["valid_until"], name="taxpayer_st_valid_u_c04efb_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TaxpayerRepresentative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company_rut",
                    models.CharField(
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator("^\\d{7,8}$")
                        ],
                    ),
                ),
                (
                    "company_dv",
                    models.CharField(
                        max_length=1,
                        validators=[django.core.validators.RegexValidator("^[0-9Kk]$")],
                    ),
                ),
                (
                    "representative_rut",
                    models.CharField(
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator("^\\d{7,8}$")
                        ],
                    ),
                ),
                (
                    "representative_dv",
                    models.CharField(
                        max_length=1,
                        validators=[django.core.validators.RegexValidator("^[0-9Kk]$")],
                    ),
                ),
                ("representative_name", models.CharField(max_length=255)),
                ("position", models.CharField(blank=True, max_length=100)),
                ("appointment_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Taxpayer Representative",
                "verbose_name_plural": "Taxpayer Representatives",
                "db_table": "taxpayer_representatives",
                "ordering": ["company_rut", "representative_name"],
                "indexes": [
                    models.Index(
                        fields=["company_rut", "company_dv"],
                        name="taxpayer_re_company_ed4413_idx",
                    ),
                    models.Index(
                        fields=["representative_rut", "representative_dv"],
                        name="taxpayer_re_represe_fd8e39_idx",
                    ),
                ],
                "unique_together": {
                    (
                        "company_rut",
                        "company_dv",
                        "representative_rut",
                        "representative_dv",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="TaxpayerPartner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company_rut",
                    models.CharField(
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator("^\\d{7,8}$")
                        ],
                    ),
                ),
                (
                    "company_dv",
                    models.CharField(
                        max_length=1,
                        validators=[django.core.validators.RegexValidator("^[0-9Kk]$")],
                    ),
                ),
                (
                    "partner_rut",
                    models.CharField(
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator("^\\d{7,8}$")
                        ],
                    ),
                ),
                (
                    "partner_dv",
                    models.CharField(
                        max_length=1,
                        validators=[django.core.validators.RegexValidator("^[0-9Kk]$")],
                    ),
                ),
                ("partner_name", models.CharField(max_length=255)),
                (
                    "partner_type",
                    models.CharField(
                        choices=[
                            ("natural", "Persona Natural"),
                            ("juridica", "Persona Jurídica"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "ownership_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("participation_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Taxpayer Partner",
                "verbose_name_plural": "Taxpayer Partners",
                "db_table": "taxpayer_partners",
                "ordering": ["company_rut", "partner_name"],
                "indexes": [
                    models.Index(
                        fields=["company_rut", "company_dv"],
                        name="taxpayer_pa_company_529ccf_idx",
                    ),
                    models.Index(
                        fields=["partner_rut", "partner_dv"],
                        name="taxpayer_pa_partner_b6104a_idx",
                    ),
                ],
                "unique_together": {
                    ("company_rut", "company_dv", "partner_rut", "partner_dv")
                },
            },
        ),
        migrations.CreateModel(
            name="TaxpayerAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "taxpayer_rut",
                    models.CharField(
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator("^\\d{7,8}$")
                        ],
                    ),
                ),
                (
                    "taxpayer_dv",
                    models.CharField(
                        max_length=1,
                        validators=[django.core.validators.RegexValidator("^[0-9Kk]$")],
                    ),
                ),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("commercial", "Comercial"),
                            ("legal", "Legal"),
                            ("postal", "Postal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("street_address", models.CharField(max_length=500)),
                ("city", models.CharField(max_length=100)),
                ("region", models.CharField(max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=10)),
                ("country", models.CharField(default="Chile", max_length=50)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Taxpayer Address",
                "verbose_name_plural": "Taxpayer Addresses",
                "db_table": "taxpayer_addresses",
                "ordering": ["taxpayer_rut", "-is_primary"],
                "indexes": [
                    models.Index(
                        fields=["taxpayer_rut", "taxpayer_dv"],
                        name="taxpayer_ad_taxpaye_fdecaa_idx",
                    )
                ],
            },
        ),
    ]
