# Generated by Django 4.2.11 on 2025-10-02 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_companysegment_processtemplateconfig_and_more"),
        ("taxpayers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxpayer",
            name="company_segment",
            field=models.ForeignKey(
                blank=True,
                help_text="Segmento al que pertenece este contribuyente para asignación automática de procesos",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="taxpayers",
                to="tasks.companysegment",
                verbose_name="Segmento de Empresa",
            ),
        ),
    ]
