# Generated by Django 4.2.11 on 2025-08-31 23:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxpayers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxPayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rut",
                    models.CharField(
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator("^\\d{7,8}$")
                        ],
                    ),
                ),
                (
                    "dv",
                    models.CharField(
                        max_length=1,
                        validators=[django.core.validators.RegexValidator("^[0-9Kk]$")],
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        help_text="RUT con formato completo del SII",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "razon_social",
                    models.CharField(
                        help_text="Razón social oficial del SII", max_length=255
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True, help_text="Nombre alternativo", max_length=255
                    ),
                ),
                (
                    "tipo_contribuyente",
                    models.CharField(
                        blank=True,
                        help_text="Ej: PERSONA JURIDICA COMERCIAL",
                        max_length=100,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        default="ACTIVO", help_text="Estado en el SII", max_length=50
                    ),
                ),
                (
                    "actividad_description",
                    models.TextField(
                        blank=True, help_text="Descripción de la actividad económica"
                    ),
                ),
                (
                    "glosa_actividad",
                    models.TextField(
                        blank=True, help_text="Glosa de la actividad del SII"
                    ),
                ),
                ("fecha_inicio_actividades", models.DateField(blank=True, null=True)),
                (
                    "direccion",
                    models.TextField(
                        blank=True, help_text="Dirección completa del SII"
                    ),
                ),
                ("comuna", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Email registrado en SII", max_length=254
                    ),
                ),
                (
                    "mobile_phone",
                    models.CharField(
                        blank=True, help_text="Teléfono del SII", max_length=20
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        default="sii_extraction",
                        help_text="Origen de los datos",
                        max_length=50,
                    ),
                ),
                (
                    "last_sii_sync",
                    models.DateTimeField(
                        blank=True, help_text="Última sincronización con SII", null=True
                    ),
                ),
                (
                    "sii_raw_data",
                    models.JSONField(
                        blank=True, help_text="Datos completos del SII", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Verificado contra SII"
                    ),
                ),
            ],
            options={
                "verbose_name": "TaxPayer",
                "verbose_name_plural": "TaxPayers",
                "db_table": "taxpayers",
                "ordering": ["razon_social"],
                "indexes": [
                    models.Index(fields=["rut", "dv"], name="taxpayers_rut_0a0e96_idx"),
                    models.Index(fields=["tax_id"], name="taxpayers_tax_id_d9ec61_idx"),
                    models.Index(
                        fields=["razon_social"], name="taxpayers_razon_s_39f5e8_idx"
                    ),
                    models.Index(fields=["estado"], name="taxpayers_estado_8412b9_idx"),
                ],
            },
        ),
    ]
