# Generated by Django 4.2.11 on 2025-09-01 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0003_add_taxpayer_reference"),
        ("taxpayers", "0002_add_taxpayer_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxpayerSiiCredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tax_id",
                    models.CharField(help_text="RUT del contribuyente", max_length=20),
                ),
                (
                    "encrypted_password",
                    models.TextField(help_text="Contraseña del SII encriptada"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "last_verified",
                    models.DateTimeField(
                        blank=True, help_text="Última verificación exitosa", null=True
                    ),
                ),
                (
                    "verification_failures",
                    models.IntegerField(
                        default=0, help_text="Contador de fallos de verificación"
                    ),
                ),
                (
                    "company",
                    models.OneToOneField(
                        help_text="Empresa asociada a estas credenciales",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxpayer_sii_credentials",
                        to="companies.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Usuario que registró estas credenciales",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Taxpayer SII Credentials",
                "verbose_name_plural": "Taxpayer SII Credentials",
                "db_table": "taxpayer_sii_credentials",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tax_id"], name="taxpayer_si_tax_id_6b47ef_idx"
                    ),
                    models.Index(
                        fields=["company"], name="taxpayer_si_company_5e498f_idx"
                    ),
                    models.Index(
                        fields=["user"], name="taxpayer_si_user_id_be4ec6_idx"
                    ),
                ],
            },
        ),
    ]
