# Generated by Django 4.2.11 on 2025-09-20 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxpayers", "0006_reverse_taxpayer_company_relationship"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taxpayeraddress",
            name="company",
        ),
        migrations.AlterUniqueTogether(
            name="taxpayerpartner",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="taxpayerpartner",
            name="company",
        ),
        migrations.AlterUniqueTogether(
            name="taxpayerrepresentative",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="taxpayerrepresentative",
            name="company",
        ),
        migrations.RemoveField(
            model_name="taxpayerstamp",
            name="company",
        ),
        migrations.DeleteModel(
            name="TaxpayerActivity",
        ),
        migrations.DeleteModel(
            name="TaxpayerAddress",
        ),
        migrations.DeleteModel(
            name="TaxpayerPartner",
        ),
        migrations.DeleteModel(
            name="TaxpayerRepresentative",
        ),
        migrations.DeleteModel(
            name="TaxpayerStamp",
        ),
    ]
