# Generated by Django 4.2.11 on 2025-09-20 15:41

from django.db import migrations, models
from django.core.validators import RegexValidator


class Migration(migrations.Migration):

    dependencies = [
        ("taxpayers", "0007_remove_taxpayeraddress_company_and_more"),
    ]

    operations = [
        # Add only essential fields
        migrations.AddField(
            model_name='taxpayer',
            name='rut',
            field=models.CharField(max_length=12, default='', blank=True),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='dv',
            field=models.CharField(max_length=1, default='', blank=True),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='razon_social',
            field=models.CharField(max_length=255, default='', blank=True),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
