# Generated by Django 4.2.11 on 2025-09-20 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxpayers", "0008_auto_20250920_1241"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxpayer",
            name="dv",
            field=models.CharField(
                max_length=1,
                validators=[django.core.validators.RegexValidator("^[0-9Kk]$")],
            ),
        ),
        migrations.AlterField(
            model_name="taxpayer",
            name="razon_social",
            field=models.CharField(
                help_text="Razón social oficial del SII", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="taxpayer",
            name="rut",
            field=models.CharField(
                max_length=12,
                validators=[django.core.validators.RegexValidator("^\\d{7,8}$")],
            ),
        ),
    ]
