# Generated by Claude Code on 2025-09-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxpayers', '0009_add_missing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxpayer',
            name='setting_procesos',
            field=models.JSONField(blank=True, default=dict, help_text='Configuración de procesos tributarios habilitados para este contribuyente'),
        ),
    ]