# Generated by Django 4.2.11 on 2025-08-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tax_type",
                    models.CharField(
                        choices=[
                            ("iva", "IVA"),
                            ("specific", "Impuesto Específico"),
                            ("additional", "Impuesto Adicional"),
                            ("retention", "Retención"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("effective_from", models.DateField()),
                ("effective_until", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Tax Rate",
                "verbose_name_plural": "Tax Rates",
                "db_table": "tax_rates",
                "ordering": ["-effective_from", "tax_type"],
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "Dólar Estadounidense"),
                            ("EUR", "Euro"),
                            ("UF", "Unidad de Fomento"),
                            ("UTM", "Unidad Tributaria Mensual"),
                            ("UTA", "Unidad Tributaria Anual"),
                        ],
                        max_length=3,
                    ),
                ),
                ("date", models.DateField()),
                ("rate", models.DecimalField(decimal_places=6, max_digits=12)),
                (
                    "source",
                    models.CharField(
                        default="SII",
                        help_text="Fuente del tipo de cambio",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Exchange Rate",
                "verbose_name_plural": "Exchange Rates",
                "db_table": "exchange_rates",
                "ordering": ["-date", "currency"],
                "unique_together": {("currency", "date")},
            },
        ),
    ]
