# Generated by Django 4.2.11 on 2025-09-23 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Process",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "process_type",
                    models.CharField(
                        choices=[
                            ("tax_monthly", "Declaración Mensual"),
                            ("tax_annual", "Declaración Anual"),
                            ("document_sync", "Sincronización Documentos"),
                            ("sii_integration", "Integración SII"),
                            ("custom", "Personalizado"),
                        ],
                        max_length=50,
                    ),
                ),
                ("company_rut", models.CharField(max_length=12)),
                ("company_dv", models.CharField(max_length=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("active", "Activo"),
                            ("paused", "Pausado"),
                            ("completed", "Completado"),
                            ("failed", "Fallido"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_template", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.CharField(
                        help_text="Email del usuario creador", max_length=255
                    ),
                ),
                (
                    "assigned_to",
                    models.CharField(
                        blank=True,
                        help_text="Email del usuario responsable",
                        max_length=255,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "config_data",
                    models.JSONField(
                        default=dict, help_text="Configuración específica del proceso"
                    ),
                ),
                (
                    "parent_process",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tasks.process",
                    ),
                ),
            ],
            options={
                "verbose_name": "Process",
                "verbose_name_plural": "Processes",
                "db_table": "processes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcessTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "process_type",
                    models.CharField(
                        choices=[
                            ("tax_monthly", "Declaración Mensual"),
                            ("tax_annual", "Declaración Anual"),
                            ("document_sync", "Sincronización Documentos"),
                            ("sii_integration", "Integración SII"),
                            ("custom", "Personalizado"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "template_data",
                    models.JSONField(
                        default=dict, help_text="Configuración de la plantilla"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.CharField(
                        help_text="Email del usuario creador", max_length=255
                    ),
                ),
            ],
            options={
                "verbose_name": "Process Template",
                "verbose_name_plural": "Process Templates",
                "db_table": "process_templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProcessExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Ejecutándose"),
                            ("paused", "Pausado"),
                            ("completed", "Completado"),
                            ("failed", "Fallido"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "execution_context",
                    models.JSONField(
                        default=dict, help_text="Contexto global de la ejecución"
                    ),
                ),
                ("current_step", models.IntegerField(default=0)),
                ("total_steps", models.IntegerField(default=0)),
                ("completed_steps", models.IntegerField(default=0)),
                ("failed_steps", models.IntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("error_count", models.IntegerField(default=0)),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="tasks.process",
                    ),
                ),
            ],
            options={
                "verbose_name": "Process Execution",
                "verbose_name_plural": "Process Executions",
                "db_table": "process_executions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcessTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("execution_order", models.IntegerField(default=0)),
                (
                    "execution_conditions",
                    models.JSONField(
                        default=dict, help_text="Condiciones para ejecutar la tarea"
                    ),
                ),
                ("is_optional", models.BooleanField(default=False)),
                ("can_run_parallel", models.BooleanField(default=False)),
                (
                    "context_data",
                    models.JSONField(
                        default=dict, help_text="Datos de contexto para la tarea"
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_tasks",
                        to="tasks.process",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_processes",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Process Task",
                "verbose_name_plural": "Process Tasks",
                "db_table": "process_tasks",
                "ordering": ["execution_order"],
                "unique_together": {("process", "task")},
            },
        ),
        migrations.AddIndex(
            model_name="process",
            index=models.Index(
                fields=["company_rut", "company_dv"],
                name="processes_company_a949ec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="process",
            index=models.Index(
                fields=["status", "process_type"], name="processes_status_1d636a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="process",
            index=models.Index(
                fields=["due_date"], name="processes_due_dat_faadfa_idx"
            ),
        ),
    ]
