# Generated by Django 4.2.11 on 2025-09-23 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_process_processtemplate_processexecution_processtask_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="process",
            name="is_recurring",
            field=models.BooleanField(
                default=False, help_text="Si este proceso se repite automáticamente"
            ),
        ),
        migrations.AddField(
            model_name="process",
            name="next_occurrence_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha en que se debe generar el siguiente proceso",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="process",
            name="recurrence_config",
            field=models.JSONField(
                default=dict,
                help_text="Configuración de recurrencia: intervalos, fechas base, etc.",
            ),
        ),
        migrations.AddField(
            model_name="process",
            name="recurrence_source",
            field=models.ForeignKey(
                blank=True,
                help_text="Proceso padre del cual se generó este por recurrencia",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recurring_instances",
                to="tasks.process",
            ),
        ),
        migrations.AddField(
            model_name="process",
            name="recurrence_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("monthly", "Mensual"),
                    ("quarterly", "Trimestral"),
                    ("annual", "Anual"),
                    ("custom", "Personalizado"),
                ],
                help_text="Tipo de recurrencia",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="processtask",
            name="absolute_due_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha límite absoluta para esta tarea (sobrescribe cálculos)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="processtask",
            name="due_date_from_previous",
            field=models.IntegerField(
                blank=True,
                help_text="Días desde completación de tarea anterior para calcular fecha límite",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="processtask",
            name="due_date_offset_days",
            field=models.IntegerField(
                blank=True,
                help_text="Días desde el inicio del proceso para calcular fecha límite",
                null=True,
            ),
        ),
    ]
