# Generated by Django 4.2.11 on 2025-09-23 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_remove_taxpayer_field"),
        ("tasks", "0003_process_is_recurring_process_next_occurrence_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="process",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa a la que pertenece este proceso",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="processes",
                to="companies.company",
            ),
        ),
    ]
