# Generated by Django 4.2.11 on 2025-09-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_process_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="process",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Borrador"),
                    ("active", "Activo"),
                    ("paused", "Pausado"),
                    ("completed", "Completado"),
                    ("failed", "Fallido"),
                    ("cancelled", "Cancelado"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
