# Generated by Django 4.2.11 on 2025-09-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                help_text="Número completo con prefijo país sin +. Ej: 56912345678",
                max_length=15,
            ),
        ),
    ]
