# Generated by Django 4.2.11 on 2025-09-12 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_role_is_active"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
