# Generated by Django 4.2.11 on 2025-09-25 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_add_verification_fields_and_model"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="verificationcode",
            unique_together=set(),
        ),
    ]
