# Generated by Django 4.2.11 on 2025-09-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_backgroundtasktracker"),
        ("accounts", "0006_userprofile_onboarding_completed_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="teaminvitation",
            name="team_invita_company_40b1d8_idx",
        ),
        migrations.AlterUniqueTogether(
            name="teaminvitation",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="teaminvitation",
            name="companies",
            field=models.ManyToManyField(
                related_name="team_invitations", to="companies.company"
            ),
        ),
        migrations.AddConstraint(
            model_name="teaminvitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("email", "status"),
                name="unique_pending_invitation_per_email",
            ),
        ),
        migrations.RemoveField(
            model_name="teaminvitation",
            name="company",
        ),
    ]
