# Generated by Django 4.2.11 on 2025-10-02 02:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0007_remove_teaminvitation_team_invita_company_40b1d8_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PreLaunchSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.EmailField(
                        help_text="Email del suscriptor interesado en el pre-lanzamiento",
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Dirección IP desde donde se registró",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="User agent del navegador"),
                ),
                (
                    "source",
                    models.CharField(
                        default="web",
                        help_text="Fuente de la suscripción (web, mobile, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "notified",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si ya se le notificó del lanzamiento",
                    ),
                ),
                (
                    "notified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha en que se le notificó del lanzamiento",
                        null=True,
                    ),
                ),
                (
                    "converted_to_user",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si el suscriptor se convirtió en usuario registrado",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notas adicionales sobre el suscriptor"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario creado a partir de este suscriptor",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pre_launch_subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pre-Launch Subscriber",
                "verbose_name_plural": "Pre-Launch Subscribers",
                "db_table": "pre_launch_subscribers",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email"], name="pre_launch__email_604b4f_idx"),
                    models.Index(
                        fields=["created_at"], name="pre_launch__created_6f78ff_idx"
                    ),
                    models.Index(
                        fields=["notified", "converted_to_user"],
                        name="pre_launch__notifie_286846_idx",
                    ),
                ],
            },
        ),
    ]
