[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = ["python311", "chromium", "chromium-chromedriver", "curl"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build]
# Skip collectstatic here - it runs in start-web.sh with proper env vars
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "chmod +x scripts/*.sh && ./scripts/start-web.sh"