# Generated by Django 4.2.11 on 2025-08-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("tax_id", models.CharField(max_length=20, unique=True)),
                ("rut", models.CharField(max_length=12)),
                ("dv", models.CharField(max_length=1)),
                ("business_name", models.CharField(blank=True, max_length=255)),
                ("company_type", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("billing_email", models.EmailField(blank=True, max_length=254)),
                ("mobile_phone", models.CharField(blank=True, max_length=20)),
                ("electronic_biller", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "db_table": "companies",
            },
        ),
    ]
