# Generated by Django 4.2.11 on 2025-09-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tax_id",
                    models.CharField(
                        help_text="RUT con formato XX.XXX.XXX-X",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "business_name",
                    models.CharField(
                        help_text="Nombre comercial elegido por el usuario",
                        max_length=255,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Nombre a mostrar en la aplicación",
                        max_length=255,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email principal de contacto", max_length=254
                    ),
                ),
                (
                    "billing_email",
                    models.EmailField(
                        blank=True, help_text="Email para facturación", max_length=254
                    ),
                ),
                (
                    "accounting_email",
                    models.EmailField(
                        blank=True, help_text="Email para contabilidad", max_length=254
                    ),
                ),
                (
                    "mobile_phone",
                    models.CharField(
                        blank=True, help_text="Teléfono de contacto", max_length=20
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, help_text="Sitio web de la empresa"),
                ),
                (
                    "electronic_biller",
                    models.BooleanField(
                        default=True, help_text="¿Emite documentos electrónicos?"
                    ),
                ),
                (
                    "preferred_currency",
                    models.CharField(
                        default="CLP", help_text="Moneda preferida", max_length=3
                    ),
                ),
                (
                    "time_zone",
                    models.CharField(
                        default="America/Santiago",
                        help_text="Zona horaria",
                        max_length=50,
                    ),
                ),
                (
                    "person_company",
                    models.CharField(
                        choices=[
                            ("PERSONA", "Persona Natural"),
                            ("EMPRESA", "Empresa/Persona Jurídica"),
                        ],
                        default="EMPRESA",
                        help_text="Clasificación para la aplicación",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("login_tries", models.IntegerField(default=0)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="companies/logos/"
                    ),
                ),
                ("notify_new_documents", models.BooleanField(default=True)),
                ("notify_tax_deadlines", models.BooleanField(default=True)),
                ("notify_system_updates", models.BooleanField(default=True)),
                ("record_created_at", models.DateTimeField(blank=True, null=True)),
                ("record_updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "db_table": "companies",
                "ordering": ["business_name"],
            },
        ),
    ]
