# Generated by Django 4.2.11 on 2025-08-31 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["name"],
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.AddField(
            model_name="company",
            name="accounting_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="company",
            name="activity_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="company",
            name="activity_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="authorized_declare_day20",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="company",
            name="capital_paid",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="capital_pending",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="company_subtype_code",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="company",
            name="company_subtype_description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="company",
            name="company_type_code",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="company",
            name="company_type_description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="company",
            name="incorporation_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="login_tries",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="company",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="companies/logos/"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="misii_person",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="company",
            name="person_company",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="company",
            name="record_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="record_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="segment_code",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="company",
            name="segment_description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="company",
            name="unit_address",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="company",
            name="unit_code",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="company",
            name="unit_description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="company",
            name="website",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="dv",
            field=models.CharField(
                max_length=1,
                validators=[django.core.validators.RegexValidator("^[0-9Kk]$")],
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="rut",
            field=models.CharField(
                max_length=12,
                validators=[django.core.validators.RegexValidator("^\\d{7,8}$")],
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="tax_id",
            field=models.CharField(
                help_text="RUT con formato XX.XXX.XXX-X", max_length=20, unique=True
            ),
        ),
    ]
