# Generated by Django 4.2.11 on 2025-09-24 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackgroundTaskTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task_id",
                    models.CharField(
                        help_text="ID único de la tarea de Celery",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "task_name",
                    models.CharField(
                        choices=[
                            (
                                "create_processes_from_taxpayer_settings",
                                "Creando procesos tributarios",
                            ),
                            ("sync_sii_documents_task", "Sincronizando documentos SII"),
                            (
                                "sync_sii_documents_full_history_task",
                                "Sincronizando historial completo SII",
                            ),
                            (
                                "sync_all_historical_forms_task",
                                "Sincronizando formularios históricos",
                            ),
                        ],
                        help_text="Nombre identificativo de la tarea",
                        max_length=100,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Nombre a mostrar al usuario", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("running", "Ejecutándose"),
                            ("success", "Completada"),
                            ("failed", "Falló"),
                        ],
                        default="pending",
                        help_text="Estado actual de la tarea",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(default=0, help_text="Progreso de 0 a 100"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Momento en que comenzó la ejecución",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Momento en que terminó la ejecución",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Mensaje de error si la tarea falló"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Información adicional sobre la tarea",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa asociada a la tarea",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="background_tasks",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Background Task Tracker",
                "verbose_name_plural": "Background Task Trackers",
                "db_table": "background_task_trackers",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "status"],
                        name="background__company_2c0967_idx",
                    ),
                    models.Index(
                        fields=["task_id"], name="background__task_id_060d2d_idx"
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="background__status_e26e11_idx",
                    ),
                ],
            },
        ),
    ]
