# Generated by Django 4.2.11 on 2025-08-31 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("taxpayers", "0002_add_taxpayer_model"),
        ("companies", "0002_alter_company_options_company_accounting_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["business_name"],
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.RemoveField(
            model_name="company",
            name="activity_description",
        ),
        migrations.RemoveField(
            model_name="company",
            name="activity_start_date",
        ),
        migrations.RemoveField(
            model_name="company",
            name="authorized_declare_day20",
        ),
        migrations.RemoveField(
            model_name="company",
            name="capital_paid",
        ),
        migrations.RemoveField(
            model_name="company",
            name="capital_pending",
        ),
        migrations.RemoveField(
            model_name="company",
            name="company_subtype_code",
        ),
        migrations.RemoveField(
            model_name="company",
            name="company_subtype_description",
        ),
        migrations.RemoveField(
            model_name="company",
            name="company_type",
        ),
        migrations.RemoveField(
            model_name="company",
            name="company_type_code",
        ),
        migrations.RemoveField(
            model_name="company",
            name="company_type_description",
        ),
        migrations.RemoveField(
            model_name="company",
            name="dv",
        ),
        migrations.RemoveField(
            model_name="company",
            name="incorporation_date",
        ),
        migrations.RemoveField(
            model_name="company",
            name="misii_person",
        ),
        migrations.RemoveField(
            model_name="company",
            name="name",
        ),
        migrations.RemoveField(
            model_name="company",
            name="rut",
        ),
        migrations.RemoveField(
            model_name="company",
            name="segment_code",
        ),
        migrations.RemoveField(
            model_name="company",
            name="segment_description",
        ),
        migrations.RemoveField(
            model_name="company",
            name="unit_address",
        ),
        migrations.RemoveField(
            model_name="company",
            name="unit_code",
        ),
        migrations.RemoveField(
            model_name="company",
            name="unit_description",
        ),
        migrations.AddField(
            model_name="company",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="Nombre a mostrar en la aplicación",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="notify_new_documents",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="company",
            name="notify_system_updates",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="company",
            name="notify_tax_deadlines",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="company",
            name="preferred_currency",
            field=models.CharField(
                default="CLP", help_text="Moneda preferida", max_length=3
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="taxpayer",
            field=models.OneToOneField(
                blank=True,
                help_text="Referencia al contribuyente con datos del SII",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company",
                to="taxpayers.taxpayer",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="time_zone",
            field=models.CharField(
                default="America/Santiago", help_text="Zona horaria", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="accounting_email",
            field=models.EmailField(
                blank=True, help_text="Email para contabilidad", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="billing_email",
            field=models.EmailField(
                blank=True, help_text="Email para facturación", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="business_name",
            field=models.CharField(
                help_text="Nombre comercial elegido por el usuario", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="electronic_biller",
            field=models.BooleanField(
                default=True, help_text="¿Emite documentos electrónicos?"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="email",
            field=models.EmailField(
                help_text="Email principal de contacto", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="mobile_phone",
            field=models.CharField(
                blank=True, help_text="Teléfono de contacto", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="person_company",
            field=models.CharField(
                choices=[
                    ("PERSONA", "Persona Natural"),
                    ("EMPRESA", "Empresa/Persona Jurídica"),
                ],
                default="EMPRESA",
                help_text="Clasificación para la aplicación",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="website",
            field=models.URLField(blank=True, help_text="Sitio web de la empresa"),
        ),
    ]
