# Generated by Django 4.2.11 on 2025-09-25 20:14

from django.db import migrations


def migrate_clients_and_providers(apps, schema_editor):
    """
    No hay datos que migrar - las apps anteriores fueron eliminadas sin datos
    """
    pass


def reverse_migrate_contacts(apps, schema_editor):
    """
    Migración reversa (no implementada por simplicidad)
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(migrate_clients_and_providers, reverse_migrate_contacts),
    ]
