# Generated by Django 4.2.11 on 2025-09-03 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhookevent",
            name="event_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("whatsapp.message.received", "Mensaje Recibido"),
                    ("whatsapp.message.sent", "Mensaje Enviado"),
                    ("whatsapp.conversation.created", "Conversación Creada"),
                    ("whatsapp.conversation.ended", "Conversación Terminada"),
                    ("whatsapp.message.delivered", "Mensaje Entregado"),
                    ("whatsapp.message.read", "Mensaje Leído"),
                    ("whatsapp.message.failed", "Mensaje Fallido"),
                    ("unknown", "Tipo Desconocido"),
                ],
                default="unknown",
                max_length=50,
                null=True,
            ),
        ),
    ]
