# Generated by Django 4.2.11 on 2025-08-31 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("issuer_company_rut", models.CharField(max_length=12)),
                ("issuer_company_dv", models.CharField(max_length=1)),
                ("issuer_name", models.CharField(max_length=255)),
                ("issuer_address", models.CharField(max_length=500)),
                ("issuer_activity", models.CharField(blank=True, max_length=255)),
                ("recipient_rut", models.CharField(max_length=12)),
                ("recipient_dv", models.CharField(max_length=1)),
                ("recipient_name", models.CharField(max_length=255)),
                ("recipient_address", models.CharField(blank=True, max_length=500)),
                ("folio", models.IntegerField()),
                ("issue_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("pending", "Pendiente"),
                            ("signed", "Firmado"),
                            ("sent", "Enviado"),
                            ("accepted", "Aceptado"),
                            ("rejected", "Rechazado"),
                            ("cancelled", "Anulado"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "exempt_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("sii_track_id", models.CharField(blank=True, max_length=50)),
                ("sii_response", models.JSONField(default=dict)),
                ("xml_data", models.TextField(blank=True)),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="documents/pdfs/"
                    ),
                ),
                ("reference_reason", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "db_table": "documents",
                "ordering": ["-issue_date", "-folio"],
            },
        ),
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.IntegerField(
                        help_text="Código SII del documento", unique=True
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("invoice", "Facturas"),
                            ("receipt", "Boletas"),
                            ("credit_note", "Notas de Crédito"),
                            ("debit_note", "Notas de Débito"),
                            ("dispatch", "Guías de Despacho"),
                            ("export", "Exportación"),
                            ("other", "Otros"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_electronic", models.BooleanField(default=True)),
                ("requires_recipient", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Document Type",
                "verbose_name_plural": "Document Types",
                "db_table": "document_types",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="DocumentTax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tax_type",
                    models.CharField(
                        choices=[
                            ("iva", "IVA"),
                            ("specific", "Impuesto Específico"),
                            ("additional", "Impuesto Adicional"),
                            ("retention", "Retención"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tax_code", models.CharField(max_length=10)),
                ("tax_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "taxable_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("tax_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxes",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Tax",
                "verbose_name_plural": "Document Taxes",
                "db_table": "document_taxes",
                "ordering": ["document", "tax_type"],
            },
        ),
        migrations.CreateModel(
            name="DocumentPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Efectivo"),
                            ("check", "Cheque"),
                            ("transfer", "Transferencia"),
                            ("credit_card", "Tarjeta de Crédito"),
                            ("debit_card", "Tarjeta de Débito"),
                            ("credit", "Crédito"),
                            ("other", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("payment_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("paid", "Pagado"),
                            ("overdue", "Vencido"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Payment",
                "verbose_name_plural": "Document Payments",
                "db_table": "document_payments",
                "ordering": ["document", "due_date"],
            },
        ),
        migrations.AddField(
            model_name="document",
            name="document_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="documents.documenttype"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="reference_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="references",
                to="documents.document",
            ),
        ),
        migrations.CreateModel(
            name="DocumentDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("line_number", models.IntegerField()),
                ("product_code", models.CharField(blank=True, max_length=50)),
                ("product_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=1, max_digits=10),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "line_net_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "line_tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "line_total_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=19, max_digits=5),
                ),
                ("is_exempt", models.BooleanField(default=False)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Detail",
                "verbose_name_plural": "Document Details",
                "db_table": "document_details",
                "ordering": ["document", "line_number"],
                "unique_together": {("document", "line_number")},
            },
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["issuer_company_rut", "issuer_company_dv"],
                name="documents_issuer__7d567b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["recipient_rut", "recipient_dv"],
                name="documents_recipie_fbe0c7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["document_type", "folio"], name="documents_documen_a0207a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["issue_date"], name="documents_issue_d_c0cf0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["status"], name="documents_status_f31a08_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="document",
            unique_together={
                ("issuer_company_rut", "issuer_company_dv", "document_type", "folio")
            },
        ),
    ]
