# Generated by Django 4.2.11 on 2025-09-24 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.IntegerField(
                        help_text="Código SII del documento", unique=True
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("invoice", "Facturas"),
                            ("receipt", "Boletas"),
                            ("credit_note", "Notas de Crédito"),
                            ("debit_note", "Notas de Débito"),
                            ("dispatch", "Guías de Despacho"),
                            ("export", "Exportación"),
                            ("other", "Otros"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_electronic", models.BooleanField(default=True)),
                (
                    "is_dte",
                    models.BooleanField(
                        default=False,
                        help_text="Es un DTE (Documento Tributario Electrónico)",
                    ),
                ),
                ("requires_recipient", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Document Type",
                "verbose_name_plural": "Document Types",
                "db_table": "document_types",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("issuer_company_rut", models.CharField(max_length=12)),
                ("issuer_company_dv", models.CharField(max_length=1)),
                ("issuer_name", models.CharField(max_length=255)),
                ("issuer_address", models.CharField(max_length=500)),
                ("issuer_activity", models.CharField(blank=True, max_length=255)),
                ("recipient_rut", models.CharField(max_length=12)),
                ("recipient_dv", models.CharField(max_length=1)),
                ("recipient_name", models.CharField(max_length=255)),
                ("recipient_address", models.CharField(blank=True, max_length=500)),
                ("folio", models.IntegerField()),
                ("issue_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("pending", "Pendiente"),
                            ("signed", "Firmado"),
                            ("sent", "Enviado al SII"),
                            ("accepted", "Aceptado por SII"),
                            ("rejected", "Rechazado por SII"),
                            ("cancelled", "Anulado"),
                            ("processed", "Procesado"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "exempt_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("sii_track_id", models.CharField(blank=True, max_length=50)),
                ("sii_response", models.JSONField(default=dict)),
                ("xml_data", models.TextField(blank=True)),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="documents/pdfs/"
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Datos originales del SII sin procesar",
                    ),
                ),
                ("reference_reason", models.CharField(blank=True, max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa propietaria del documento (emisor para docs emitidos, receptor para docs recibidos)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="companies.company",
                    ),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="documents.documenttype",
                    ),
                ),
                (
                    "reference_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="references",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "db_table": "documents",
                "ordering": ["-issue_date", "-folio"],
                "indexes": [
                    models.Index(
                        fields=["issuer_company_rut", "issuer_company_dv"],
                        name="documents_issuer__7d567b_idx",
                    ),
                    models.Index(
                        fields=["recipient_rut", "recipient_dv"],
                        name="documents_recipie_fbe0c7_idx",
                    ),
                    models.Index(
                        fields=["document_type", "folio"],
                        name="documents_documen_a0207a_idx",
                    ),
                    models.Index(
                        fields=["issue_date"], name="documents_issue_d_c0cf0d_idx"
                    ),
                    models.Index(fields=["status"], name="documents_status_f31a08_idx"),
                ],
                "unique_together": {
                    (
                        "issuer_company_rut",
                        "issuer_company_dv",
                        "document_type",
                        "folio",
                    )
                },
            },
        ),
    ]
