# Generated by Django 4.2.11 on 2025-09-24 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_backgroundtasktracker"),
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa propietaria del documento (emisor para docs emitidos, receptor para docs recibidos)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="companies.company",
            ),
        ),
    ]
