# Generated by Django 4.2.11 on 2025-09-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documenttype",
            name="is_dte",
            field=models.BooleanField(
                default=False, help_text="Es un DTE (Documento Tributario Electrónico)"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Borrador"),
                    ("pending", "Pendiente"),
                    ("signed", "Firmado"),
                    ("sent", "Enviado al SII"),
                    ("accepted", "Aceptado por SII"),
                    ("rejected", "Rechazado por SII"),
                    ("cancelled", "Anulado"),
                    ("processed", "Procesado"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
