# Generated by Django 4.2.11 on 2025-09-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_alter_document_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="reference_folio",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="document",
            name="reference_folio_type",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
