# Generated by Django 4.2.11 on 2025-09-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_documenttype_is_dte_alter_document_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="raw_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Datos originales del SII sin procesar",
            ),
        ),
    ]
