# Generated by Django 4.2.11 on 2025-09-10 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_remove_taxpayer_field"),
        ("documents", "0003_document_raw_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa propietaria del documento (emisor para docs emitidos, receptor para docs recibidos)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="companies.company",
            ),
        ),
    ]
