# Generated by Django 4.2.11 on 2025-09-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_document_reference_folio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="reference_folio",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="reference_folio_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
