# Generated by Django 4.2.11 on 2025-09-10 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_add_company_fk_nullable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentpayment",
            name="document",
        ),
        migrations.RemoveField(
            model_name="documenttax",
            name="document",
        ),
        migrations.DeleteModel(
            name="DocumentDetail",
        ),
        migrations.DeleteModel(
            name="DocumentPayment",
        ),
        migrations.DeleteModel(
            name="DocumentTax",
        ),
    ]
