# Generated by Django 4.2.11 on 2025-08-31 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OnboardingProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_email", models.EmailField(max_length=254, unique=True)),
                ("total_steps", models.IntegerField(default=0)),
                ("completed_steps", models.IntegerField(default=0)),
                (
                    "progress_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("last_activity", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Onboarding Progress",
                "verbose_name_plural": "Onboarding Progress",
                "db_table": "onboarding_progress",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OnboardingStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("step_order", models.IntegerField()),
                ("is_required", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "step_config",
                    models.JSONField(
                        default=dict, help_text="Configuración específica del paso"
                    ),
                ),
            ],
            options={
                "verbose_name": "Onboarding Step",
                "verbose_name_plural": "Onboarding Steps",
                "db_table": "onboarding_steps",
                "ordering": ["step_order"],
            },
        ),
        migrations.CreateModel(
            name="UserOnboarding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_email", models.EmailField(max_length=254)),
                ("company_rut", models.CharField(blank=True, max_length=12)),
                ("company_dv", models.CharField(blank=True, max_length=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "No Iniciado"),
                            ("in_progress", "En Progreso"),
                            ("completed", "Completado"),
                            ("skipped", "Omitido"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "step_data",
                    models.JSONField(
                        default=dict, help_text="Datos específicos del paso"
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="onboarding.onboardingstep",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Onboarding",
                "verbose_name_plural": "User Onboarding",
                "db_table": "user_onboarding",
                "ordering": ["step__step_order"],
                "unique_together": {("user_email", "step")},
            },
        ),
    ]
