# Generated by Django 4.2.11 on 2025-10-01 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("onboarding", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="useronboarding",
            unique_together={("user_email", "step")},
        ),
        migrations.AddField(
            model_name="useronboarding",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="onboarding_steps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="useronboarding",
            unique_together={("user_email", "step"), ("user", "step")},
        ),
    ]
