# Generated by Django 4.2.11 on 2025-09-27 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_backgroundtasktracker"),
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(help_text="Employee email address", max_length=254),
        ),
        migrations.AlterField(
            model_name="employee",
            name="tax_id",
            field=models.CharField(
                help_text="Employee RUT with format XX.XXX.XXX-X",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="RUT must be in format XX.XXX.XXX-X",
                        regex="^\\d{1,2}\\.\\d{3}\\.\\d{3}-[\\dkK]$",
                    )
                ],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="employee",
            unique_together={("email", "company"), ("tax_id", "company")},
        ),
    ]
