# Generated by Django 4.2.11 on 2025-09-24 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company_rut", models.CharField(max_length=12)),
                ("company_dv", models.CharField(max_length=1)),
                ("tax_year", models.IntegerField()),
                (
                    "tax_month",
                    models.IntegerField(
                        blank=True, help_text="Para formularios mensuales", null=True
                    ),
                ),
                (
                    "tax_period",
                    models.CharField(
                        help_text="Período en formato YYYY-MM o YYYY", max_length=20
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("in_progress", "En Progreso"),
                            ("completed", "Completado"),
                            ("validated", "Validado"),
                            ("submitted", "Enviado"),
                            ("accepted", "Aceptado"),
                            ("rejected", "Rechazado"),
                            ("paid", "Pagado"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("submission_date", models.DateTimeField(blank=True, null=True)),
                (
                    "form_data",
                    models.JSONField(
                        default=dict, help_text="Datos completados del formulario"
                    ),
                ),
                (
                    "calculated_values",
                    models.JSONField(
                        default=dict, help_text="Valores calculados automáticamente"
                    ),
                ),
                (
                    "validation_errors",
                    models.JSONField(default=list, help_text="Errores de validación"),
                ),
                (
                    "total_tax_due",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "total_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "balance_due",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("sii_folio", models.CharField(blank=True, max_length=50)),
                ("sii_response", models.JSONField(default=dict)),
                (
                    "details_extracted",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si se extrajeron los detalles completos del formulario F29",
                    ),
                ),
                (
                    "details_extracted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora cuando se extrajeron los detalles del formulario",
                        null=True,
                    ),
                ),
                (
                    "details_extraction_method",
                    models.CharField(
                        blank=True,
                        help_text="Método usado para extraer detalles (f29_rpa, manual, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "details_data",
                    models.JSONField(
                        default=dict,
                        help_text="Datos detallados extraídos del formulario (campos específicos, subtablas, etc.)",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tax Form",
                "verbose_name_plural": "Tax Forms",
                "db_table": "tax_forms",
                "ordering": ["-tax_year", "-tax_month", "template__form_code"],
            },
        ),
        migrations.CreateModel(
            name="TaxFormTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("form_code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("f29", "Formulario 29 - Declaración Mensual IVA"),
                            (
                                "f3323",
                                "Formulario 3323 - Pago Provisional Mensual Renta",
                            ),
                            ("f50", "Formulario 50 - Declaración Anual Renta"),
                            ("f1924", "Formulario 1924 - Solicitud de Devolución"),
                            ("f1923", "Formulario 1923 - Declaración Jurada"),
                            ("f22", "Formulario 22 - Declaración Anual Renta"),
                        ],
                        max_length=10,
                    ),
                ),
                ("version", models.CharField(default="1.0", max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "form_structure",
                    models.JSONField(
                        default=dict, help_text="Estructura de campos del formulario"
                    ),
                ),
                (
                    "validation_rules",
                    models.JSONField(default=dict, help_text="Reglas de validación"),
                ),
                (
                    "calculation_rules",
                    models.JSONField(
                        default=dict, help_text="Reglas de cálculo automático"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tax Form Template",
                "verbose_name_plural": "Tax Form Templates",
                "db_table": "tax_form_templates",
                "ordering": ["form_code"],
            },
        ),
        migrations.CreateModel(
            name="TaxFormPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("online", "Pago en Línea"),
                            ("bank", "Banco"),
                            ("check", "Cheque"),
                            ("cash", "Efectivo"),
                            ("offset", "Compensación"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("payment_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("processing", "Procesando"),
                            ("completed", "Completado"),
                            ("failed", "Fallido"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("bank_code", models.CharField(blank=True, max_length=10)),
                ("transaction_id", models.CharField(blank=True, max_length=100)),
                ("authorization_code", models.CharField(blank=True, max_length=50)),
                ("receipt_number", models.CharField(blank=True, max_length=50)),
                ("sii_payment_id", models.CharField(blank=True, max_length=50)),
                ("sii_response", models.JSONField(default=dict)),
                ("notes", models.TextField(blank=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="forms.taxform",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tax Form Payment",
                "verbose_name_plural": "Tax Form Payments",
                "db_table": "tax_form_payments",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="TaxFormAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_email", models.EmailField(max_length=254)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Creado"),
                            ("updated", "Actualizado"),
                            ("validated", "Validado"),
                            ("submitted", "Enviado"),
                            ("payment_added", "Pago Agregado"),
                            ("status_changed", "Estado Cambiado"),
                            ("deleted", "Eliminado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "old_values",
                    models.JSONField(default=dict, help_text="Valores anteriores"),
                ),
                (
                    "new_values",
                    models.JSONField(default=dict, help_text="Valores nuevos"),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="forms.taxform",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tax Form Audit Log",
                "verbose_name_plural": "Tax Form Audit Logs",
                "db_table": "tax_form_audit_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="taxform",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="forms.taxformtemplate"
            ),
        ),
        migrations.CreateModel(
            name="TaxFormField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("field_code", models.CharField(max_length=20)),
                ("field_name", models.CharField(max_length=255)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Texto"),
                            ("number", "Número"),
                            ("decimal", "Decimal"),
                            ("date", "Fecha"),
                            ("boolean", "Booleano"),
                            ("select", "Selección"),
                            ("calculation", "Cálculo"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True, help_text="Sección del formulario", max_length=50
                    ),
                ),
                ("line_number", models.IntegerField(blank=True, null=True)),
                ("text_value", models.TextField(blank=True)),
                ("number_value", models.BigIntegerField(blank=True, null=True)),
                (
                    "decimal_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("date_value", models.DateField(blank=True, null=True)),
                ("boolean_value", models.BooleanField(blank=True, null=True)),
                ("is_required", models.BooleanField(default=False)),
                ("is_calculated", models.BooleanField(default=False)),
                (
                    "calculation_formula",
                    models.TextField(blank=True, help_text="Fórmula de cálculo"),
                ),
                ("validation_rules", models.JSONField(default=dict)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="forms.taxform",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tax Form Field",
                "verbose_name_plural": "Tax Form Fields",
                "db_table": "tax_form_fields",
                "ordering": ["section", "line_number", "field_code"],
                "unique_together": {("form", "field_code")},
            },
        ),
        migrations.AddIndex(
            model_name="taxform",
            index=models.Index(
                fields=["company_rut", "company_dv"],
                name="tax_forms_company_0c576c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="taxform",
            index=models.Index(fields=["company"], name="tax_forms_company_437d6f_idx"),
        ),
        migrations.AddIndex(
            model_name="taxform",
            index=models.Index(
                fields=["template", "tax_period"], name="tax_forms_templat_ce9775_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taxform",
            index=models.Index(
                fields=["status", "due_date"], name="tax_forms_status_bfdbc9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taxform",
            index=models.Index(
                fields=["details_extracted"], name="tax_forms_details_19bdd7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taxform",
            index=models.Index(
                fields=["details_extracted_at"], name="tax_forms_details_63c20d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taxform",
            unique_together={
                ("company_rut", "company_dv", "template", "tax_period"),
                ("company", "template", "tax_period"),
            },
        ),
    ]
