# Generated by Django 4.2.11 on 2025-09-22 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_remove_taxpayer_field"),
        ("forms", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="taxform",
            unique_together={("company_rut", "company_dv", "template", "tax_period")},
        ),
        migrations.AddField(
            model_name="taxform",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="companies.company",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taxform",
            unique_together={
                ("company_rut", "company_dv", "template", "tax_period"),
                ("company", "template", "tax_period"),
            },
        ),
        migrations.AddIndex(
            model_name="taxform",
            index=models.Index(fields=["company"], name="tax_forms_company_437d6f_idx"),
        ),
    ]
