# Generated by Django 4.2.11 on 2025-09-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0003_populate_company_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxform",
            name="details_data",
            field=models.JSONField(
                default=dict,
                help_text="Datos detallados extraídos del formulario (campos específicos, subtablas, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="taxform",
            name="details_extracted",
            field=models.BooleanField(
                default=False,
                help_text="Indica si se extrajeron los detalles completos del formulario F29",
            ),
        ),
        migrations.AddField(
            model_name="taxform",
            name="details_extracted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha y hora cuando se extrajeron los detalles del formulario",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="taxform",
            name="details_extraction_method",
            field=models.CharField(
                blank=True,
                help_text="Método usado para extraer detalles (f29_rpa, manual, etc.)",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="taxform",
            index=models.Index(
                fields=["details_extracted"], name="tax_forms_details_19bdd7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taxform",
            index=models.Index(
                fields=["details_extracted_at"], name="tax_forms_details_63c20d_idx"
            ),
        ),
    ]
