# Generated by Django 4.2.11 on 2025-09-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SIISession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company_rut", models.CharField(max_length=12)),
                ("company_dv", models.CharField(max_length=1)),
                ("username", models.CharField(max_length=100)),
                ("session_id", models.CharField(max_length=255, unique=True)),
                ("session_token", models.TextField(blank=True)),
                ("cookies_data", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SII Session",
                "verbose_name_plural": "SII Sessions",
                "db_table": "sii_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SIISyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company_rut", models.CharField(max_length=12)),
                ("company_dv", models.CharField(max_length=1)),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("taxpayer_info", "Información de Contribuyente"),
                            ("tax_forms", "Formularios Tributarios"),
                            ("electronic_docs", "Documentos Electrónicos"),
                            ("documents", "Documentos Tributarios"),
                            ("activities", "Actividades Económicas"),
                            ("addresses", "Direcciones"),
                            ("partners", "Socios"),
                            ("representatives", "Representantes"),
                            ("stamps", "Timbres"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "En Ejecución"),
                            ("completed", "Completado"),
                            ("failed", "Fallido"),
                            ("success", "Exitoso"),
                            ("error", "Error"),
                            ("partial", "Parcial"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("records_processed", models.IntegerField(default=0)),
                ("records_created", models.IntegerField(default=0)),
                ("records_updated", models.IntegerField(default=0)),
                ("records_failed", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("task_id", models.CharField(blank=True, max_length=255, null=True)),
                ("fecha_desde", models.DateField(blank=True, null=True)),
                ("fecha_hasta", models.DateField(blank=True, null=True)),
                ("user_email", models.EmailField(blank=True, max_length=254)),
                ("priority", models.CharField(default="normal", max_length=10)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("documents_processed", models.IntegerField(default=0)),
                ("documents_created", models.IntegerField(default=0)),
                ("documents_updated", models.IntegerField(default=0)),
                ("errors_count", models.IntegerField(default=0)),
                ("results_data", models.JSONField(default=dict)),
                ("sync_data", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "SII Sync Log",
                "verbose_name_plural": "SII Sync Logs",
                "db_table": "sii_sync_logs",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["company_rut", "company_dv"],
                        name="sii_sync_lo_company_aa982f_idx",
                    ),
                    models.Index(
                        fields=["sync_type", "status"],
                        name="sii_sync_lo_sync_ty_d72c36_idx",
                    ),
                    models.Index(
                        fields=["started_at"], name="sii_sync_lo_started_372acd_idx"
                    ),
                    models.Index(
                        fields=["task_id"], name="sii_sync_lo_task_id_c46967_idx"
                    ),
                ],
            },
        ),
    ]
