# Generated by Django 4.2.11 on 2025-08-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SIISession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company_rut", models.CharField(max_length=12)),
                ("company_dv", models.CharField(max_length=1)),
                ("username", models.CharField(max_length=100)),
                ("session_id", models.CharField(max_length=255, unique=True)),
                ("session_token", models.TextField(blank=True)),
                ("cookies_data", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SII Session",
                "verbose_name_plural": "SII Sessions",
                "db_table": "sii_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SIITaxForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company_rut", models.CharField(max_length=12)),
                ("company_dv", models.CharField(max_length=1)),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("f29", "Formulario 29"),
                            ("f3323", "Formulario 3323"),
                            ("f50", "Formulario 50"),
                            ("f1924", "Formulario 1924"),
                            ("f1923", "Formulario 1923"),
                        ],
                        max_length=10,
                    ),
                ),
                ("period_year", models.IntegerField()),
                ("period_month", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("pending", "Pendiente"),
                            ("submitted", "Enviado"),
                            ("accepted", "Aceptado"),
                            ("rejected", "Rechazado"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("form_data", models.JSONField(default=dict)),
                ("sii_folio", models.CharField(blank=True, max_length=50)),
                ("submission_date", models.DateTimeField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "total_tax_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "SII Tax Form",
                "verbose_name_plural": "SII Tax Forms",
                "db_table": "sii_tax_forms",
                "ordering": ["-period_year", "-period_month", "form_type"],
                "indexes": [
                    models.Index(
                        fields=["company_rut", "company_dv"],
                        name="sii_tax_for_company_bb6fcc_idx",
                    ),
                    models.Index(
                        fields=["form_type", "period_year", "period_month"],
                        name="sii_tax_for_form_ty_ce0b32_idx",
                    ),
                    models.Index(
                        fields=["status"], name="sii_tax_for_status_2e5bd0_idx"
                    ),
                ],
                "unique_together": {
                    (
                        "company_rut",
                        "company_dv",
                        "form_type",
                        "period_year",
                        "period_month",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="SIISyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company_rut", models.CharField(max_length=12)),
                ("company_dv", models.CharField(max_length=1)),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("taxpayer_info", "Información de Contribuyente"),
                            ("tax_forms", "Formularios Tributarios"),
                            ("electronic_docs", "Documentos Electrónicos"),
                            ("activities", "Actividades Económicas"),
                            ("addresses", "Direcciones"),
                            ("partners", "Socios"),
                            ("representatives", "Representantes"),
                            ("stamps", "Timbres"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "En Ejecución"),
                            ("success", "Exitoso"),
                            ("error", "Error"),
                            ("partial", "Parcial"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("records_processed", models.IntegerField(default=0)),
                ("records_created", models.IntegerField(default=0)),
                ("records_updated", models.IntegerField(default=0)),
                ("records_failed", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("sync_data", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "SII Sync Log",
                "verbose_name_plural": "SII Sync Logs",
                "db_table": "sii_sync_logs",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["company_rut", "company_dv"],
                        name="sii_sync_lo_company_aa982f_idx",
                    ),
                    models.Index(
                        fields=["sync_type", "status"],
                        name="sii_sync_lo_sync_ty_d72c36_idx",
                    ),
                    models.Index(
                        fields=["started_at"], name="sii_sync_lo_started_372acd_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SIIElectronicDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company_rut", models.CharField(max_length=12)),
                ("company_dv", models.CharField(max_length=1)),
                (
                    "document_type",
                    models.IntegerField(
                        choices=[
                            (33, "Factura Electrónica"),
                            (34, "Factura No Afecta o Exenta Electrónica"),
                            (39, "Boleta Electrónica"),
                            (41, "Boleta No Afecta o Exenta Electrónica"),
                            (46, "Factura de Compra Electrónica"),
                            (52, "Guía de Despacho Electrónica"),
                            (56, "Nota de Débito Electrónica"),
                            (61, "Nota de Crédito Electrónica"),
                            (110, "Factura de Exportación Electrónica"),
                            (111, "Nota de Débito de Exportación Electrónica"),
                            (112, "Nota de Crédito de Exportación Electrónica"),
                        ]
                    ),
                ),
                ("folio", models.IntegerField()),
                ("issue_date", models.DateField()),
                ("recipient_rut", models.CharField(max_length=12)),
                ("recipient_dv", models.CharField(max_length=1)),
                ("recipient_name", models.CharField(max_length=255)),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("tax_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("signed", "Firmado"),
                            ("sent", "Enviado al SII"),
                            ("accepted", "Aceptado"),
                            ("rejected", "Rechazado"),
                            ("cancelled", "Anulado"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("xml_data", models.TextField(blank=True)),
                ("sii_track_id", models.CharField(blank=True, max_length=50)),
                ("sii_response", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "SII Electronic Document",
                "verbose_name_plural": "SII Electronic Documents",
                "db_table": "sii_electronic_documents",
                "ordering": ["-issue_date", "-folio"],
                "indexes": [
                    models.Index(
                        fields=["company_rut", "company_dv"],
                        name="sii_electro_company_b87120_idx",
                    ),
                    models.Index(
                        fields=["document_type", "folio"],
                        name="sii_electro_documen_894a8d_idx",
                    ),
                    models.Index(
                        fields=["issue_date"], name="sii_electro_issue_d_f4699c_idx"
                    ),
                    models.Index(
                        fields=["status"], name="sii_electro_status_f95526_idx"
                    ),
                ],
                "unique_together": {
                    ("company_rut", "company_dv", "document_type", "folio")
                },
            },
        ),
        migrations.CreateModel(
            name="SIICredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company_rut", models.CharField(max_length=12)),
                ("company_dv", models.CharField(max_length=1)),
                ("username", models.CharField(max_length=100)),
                ("password_hash", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "SII Credential",
                "verbose_name_plural": "SII Credentials",
                "db_table": "sii_credentials",
                "ordering": ["company_rut"],
                "unique_together": {("company_rut", "company_dv", "username")},
            },
        ),
    ]
