# Generated by Django 4.2.11 on 2025-10-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sii", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="siisynclog",
            name="progress_percentage",
            field=models.IntegerField(
                default=0, help_text="Porcentaje de progreso de la sincronización"
            ),
        ),
    ]
