# Generated by Django 4.2.11 on 2025-09-01 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sii", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SIICredential",
        ),
    ]
