# Generated by Django 4.2.11 on 2025-09-02 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sii", "0002_remove_sii_credential_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="siisynclog",
            name="description",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="siisynclog",
            name="documents_created",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="siisynclog",
            name="documents_processed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="siisynclog",
            name="documents_updated",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="siisynclog",
            name="errors_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="siisynclog",
            name="fecha_desde",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siisynclog",
            name="fecha_hasta",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siisynclog",
            name="priority",
            field=models.CharField(default="normal", max_length=10),
        ),
        migrations.AddField(
            model_name="siisynclog",
            name="results_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="siisynclog",
            name="task_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siisynclog",
            name="user_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="siisynclog",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "En Ejecución"),
                    ("completed", "Completado"),
                    ("failed", "Fallido"),
                    ("success", "Exitoso"),
                    ("error", "Error"),
                    ("partial", "Parcial"),
                ],
                default="running",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="siisynclog",
            name="sync_type",
            field=models.CharField(
                choices=[
                    ("taxpayer_info", "Información de Contribuyente"),
                    ("tax_forms", "Formularios Tributarios"),
                    ("electronic_docs", "Documentos Electrónicos"),
                    ("documents", "Documentos Tributarios"),
                    ("activities", "Actividades Económicas"),
                    ("addresses", "Direcciones"),
                    ("partners", "Socios"),
                    ("representatives", "Representantes"),
                    ("stamps", "Timbres"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="siisynclog",
            index=models.Index(
                fields=["task_id"], name="sii_sync_lo_task_id_c46967_idx"
            ),
        ),
    ]
