# Generated by Django 4.2.11 on 2025-09-04 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sii", "0003_siisynclog_description_siisynclog_documents_created_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SIIElectronicDocument",
        ),
        migrations.DeleteModel(
            name="SIITaxForm",
        ),
    ]
