# Generated by Django 4.2.11 on 2025-09-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalyticsReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company_rut", models.CharField(max_length=12)),
                ("company_dv", models.CharField(max_length=1)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("tax_summary", "Resumen Tributario"),
                            ("expense_analysis", "Análisis de Gastos"),
                            ("revenue_analysis", "Análisis de Ingresos"),
                            ("cash_flow", "Flujo de Caja"),
                            ("profitability", "Rentabilidad"),
                            ("tax_compliance", "Cumplimiento Tributario"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("report_data", models.JSONField(default=dict)),
                ("generated_by", models.EmailField(max_length=254)),
                ("file_path", models.CharField(blank=True, max_length=500)),
            ],
            options={
                "verbose_name": "Analytics Report",
                "verbose_name_plural": "Analytics Reports",
                "db_table": "analytics_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company_rut", models.CharField(max_length=12)),
                ("company_dv", models.CharField(max_length=1)),
                ("metric_name", models.CharField(max_length=100)),
                ("metric_value", models.DecimalField(decimal_places=6, max_digits=20)),
                ("metric_date", models.DateField()),
            ],
            options={
                "verbose_name": "Metric",
                "verbose_name_plural": "Metrics",
                "db_table": "metrics",
                "unique_together": {
                    ("company_rut", "company_dv", "metric_name", "metric_date")
                },
            },
        ),
    ]
