# Generated by Django 4.2.11 on 2025-09-24 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("code", models.CharField(blank=True, max_length=20, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="expenses.expensecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense Category",
                "verbose_name_plural": "Expense Categories",
                "db_table": "expense_categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company_rut", models.CharField(max_length=12)),
                ("company_dv", models.CharField(max_length=1)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("supplier_rut", models.CharField(blank=True, max_length=12)),
                ("supplier_dv", models.CharField(blank=True, max_length=1)),
                ("supplier_name", models.CharField(max_length=255)),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("expense_date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("pending", "Pendiente"),
                            ("approved", "Aprobado"),
                            ("rejected", "Rechazado"),
                            ("paid", "Pagado"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_by", models.EmailField(max_length=254)),
                ("approved_by", models.EmailField(blank=True, max_length=254)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("invoice_number", models.CharField(blank=True, max_length=50)),
                (
                    "receipt_file",
                    models.FileField(
                        blank=True, null=True, upload_to="expenses/receipts/"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="expenses.expensecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense",
                "verbose_name_plural": "Expenses",
                "db_table": "expenses",
                "ordering": ["-expense_date"],
                "indexes": [
                    models.Index(
                        fields=["company_rut", "company_dv"],
                        name="expenses_company_ea0b37_idx",
                    ),
                    models.Index(
                        fields=["expense_date"], name="expenses_expense_43600a_idx"
                    ),
                    models.Index(fields=["status"], name="expenses_status_86293f_idx"),
                ],
            },
        ),
    ]
