# Generated by Django 4.2.11 on 2025-08-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_email", models.EmailField(max_length=254)),
                ("notification_type", models.CharField(max_length=50)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push"),
                            ("in_app", "En la App"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
                "db_table": "notification_preferences",
                "unique_together": {("user_email", "notification_type", "channel")},
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_email", models.EmailField(max_length=254)),
                ("company_rut", models.CharField(blank=True, max_length=12)),
                ("company_dv", models.CharField(blank=True, max_length=1)),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("info", "Información"),
                            ("warning", "Advertencia"),
                            ("error", "Error"),
                            ("success", "Éxito"),
                            ("reminder", "Recordatorio"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "action_url",
                    models.URLField(blank=True, help_text="URL de acción relacionada"),
                ),
                ("metadata", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user_email", "is_read"],
                        name="notificatio_user_em_8b4294_idx",
                    ),
                    models.Index(
                        fields=["company_rut", "company_dv"],
                        name="notificatio_company_ee1c6a_idx",
                    ),
                ],
            },
        ),
    ]
