# Generated by Django 4.2.11 on 2025-09-01 11:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0004_remove_taxpayer_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "config_id",
                    models.CharField(
                        help_text="ID de configuración en Kapso",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "phone_number_id",
                    models.CharField(
                        help_text="ID del número de teléfono en WhatsApp Business",
                        max_length=255,
                    ),
                ),
                (
                    "business_account_id",
                    models.CharField(
                        help_text="ID de la cuenta de negocio", max_length=255
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Número de teléfono con formato internacional",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+\\d{1,15}$", "Formato: +1234567890"
                            )
                        ],
                    ),
                ),
                (
                    "display_phone_number",
                    models.CharField(
                        help_text="Número formateado para mostrar", max_length=30
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Nombre a mostrar en WhatsApp", max_length=100
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_coexistence",
                    models.BooleanField(
                        default=False,
                        help_text="¿Permite coexistencia con WhatsApp Business?",
                    ),
                ),
                ("webhook_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "api_token",
                    models.CharField(help_text="Token de API de Kapso", max_length=500),
                ),
                (
                    "webhook_secret",
                    models.CharField(
                        help_text="Secreto para validar webhooks", max_length=255
                    ),
                ),
                ("enable_auto_responses", models.BooleanField(default=True)),
                ("business_hours_start", models.TimeField(default="09:00")),
                ("business_hours_end", models.TimeField(default="18:00")),
                (
                    "company",
                    models.OneToOneField(
                        help_text="Empresa asociada",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_config",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "WhatsApp Configuration",
                "verbose_name_plural": "WhatsApp Configurations",
                "db_table": "whatsapp_configs",
            },
        ),
        migrations.CreateModel(
            name="WhatsAppConversation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "conversation_id",
                    models.CharField(
                        help_text="ID de conversación en Kapso",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Número del cliente",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+\\d{1,15}$", "Formato: +1234567890"
                            )
                        ],
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, help_text="Nombre del contacto", max_length=100
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activa"),
                            ("ended", "Terminada"),
                            ("archived", "Archivada"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("last_active_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Etiquetas para clasificar la conversación",
                    ),
                ),
                ("message_count", models.PositiveIntegerField(default=0)),
                ("unread_count", models.PositiveIntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_conversations",
                        to="companies.company",
                    ),
                ),
                (
                    "whatsapp_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="chat.whatsappconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "WhatsApp Conversation",
                "verbose_name_plural": "WhatsApp Conversations",
                "db_table": "whatsapp_conversations",
                "ordering": ["-last_active_at"],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppMessage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message_id",
                    models.CharField(
                        help_text="ID del mensaje en Kapso", max_length=255, unique=True
                    ),
                ),
                (
                    "whatsapp_message_id",
                    models.CharField(
                        blank=True,
                        help_text="ID del mensaje en WhatsApp",
                        max_length=255,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Texto"),
                            ("image", "Imagen"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("voice", "Nota de voz"),
                            ("document", "Documento"),
                            ("location", "Ubicación"),
                            ("contact", "Contacto"),
                            ("interactive", "Interactivo"),
                            ("template", "Plantilla"),
                            ("reaction", "Reacción"),
                            ("system", "Sistema"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Entrante"), ("outbound", "Saliente")],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField(help_text="Contenido del mensaje")),
                ("message_type_data", models.JSONField(blank=True, default=dict)),
                ("has_media", models.BooleanField(default=False)),
                ("media_data", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Recibido"),
                            ("sent", "Enviado"),
                            ("delivered", "Entregado"),
                            ("read", "Leído"),
                            ("failed", "Fallido"),
                            ("pending", "Pendiente"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("processing", "Procesando"),
                            ("processed", "Procesado"),
                            ("failed", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("is_auto_response", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_messages",
                        to="companies.company",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.whatsappconversation",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Mensaje que generó esta respuesta automática",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auto_responses",
                        to="chat.whatsappmessage",
                    ),
                ),
            ],
            options={
                "verbose_name": "WhatsApp Message",
                "verbose_name_plural": "WhatsApp Messages",
                "db_table": "whatsapp_messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        help_text="Clave de idempotencia del webhook",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("whatsapp.message.received", "Mensaje Recibido"),
                            ("whatsapp.message.sent", "Mensaje Enviado"),
                            ("whatsapp.conversation.created", "Conversación Creada"),
                            ("whatsapp.conversation.ended", "Conversación Terminada"),
                            ("whatsapp.message.delivered", "Mensaje Entregado"),
                            ("whatsapp.message.read", "Mensaje Leído"),
                            ("whatsapp.message.failed", "Mensaje Fallido"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "webhook_signature",
                    models.CharField(
                        help_text="Firma HMAC del webhook", max_length=255
                    ),
                ),
                (
                    "raw_payload",
                    models.JSONField(help_text="Payload completo del webhook"),
                ),
                (
                    "processed_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Datos procesados del webhook",
                    ),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("processing", "Procesando"),
                            ("processed", "Procesado"),
                            ("failed", "Error"),
                            ("ignored", "Ignorado"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("processing_attempts", models.PositiveIntegerField(default=0)),
                ("processing_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processing_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("error_message", models.TextField(blank=True)),
                ("error_details", models.JSONField(blank=True, default=dict)),
                (
                    "is_test",
                    models.BooleanField(
                        default=False, help_text="¿Es un webhook de prueba?"
                    ),
                ),
                (
                    "is_batch",
                    models.BooleanField(
                        default=False,
                        help_text="¿Es un webhook con múltiples mensajes?",
                    ),
                ),
                ("batch_size", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_events",
                        to="companies.company",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_events",
                        to="chat.whatsappconversation",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_events",
                        to="chat.whatsappmessage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Event",
                "verbose_name_plural": "Webhook Events",
                "db_table": "webhook_events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre identificatorio de la plantilla",
                        max_length=100,
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("tax_reminder", "Recordatorio Tributario"),
                            ("document_alert", "Alerta de Documento"),
                            ("payment_due", "Vencimiento de Pago"),
                            ("welcome", "Bienvenida"),
                            ("support", "Soporte"),
                            ("custom", "Personalizado"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("es", "Español"),
                            ("es_CL", "Español (Chile)"),
                            ("en", "Inglés"),
                        ],
                        default="es_CL",
                        max_length=10,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="Asunto o título del mensaje",
                        max_length=200,
                    ),
                ),
                (
                    "body_text",
                    models.TextField(
                        help_text="Texto del mensaje con variables {variable}"
                    ),
                ),
                (
                    "footer_text",
                    models.CharField(
                        blank=True, help_text="Pie del mensaje", max_length=60
                    ),
                ),
                (
                    "available_variables",
                    models.JSONField(
                        default=list,
                        help_text="Lista de variables disponibles para esta plantilla",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False, help_text="¿Está aprobada por WhatsApp Business?"
                    ),
                ),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_templates",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Template",
                "verbose_name_plural": "Message Templates",
                "db_table": "whatsapp_message_templates",
                "ordering": ["template_type", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="whatsappmessage",
            index=models.Index(
                fields=["conversation", "direction"],
                name="whatsapp_me_convers_ebd3fb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappmessage",
            index=models.Index(
                fields=["company", "status"], name="whatsapp_me_company_0baf0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappmessage",
            index=models.Index(
                fields=["message_type", "direction"],
                name="whatsapp_me_message_2207ea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappmessage",
            index=models.Index(
                fields=["created_at"], name="whatsapp_me_created_f7fc48_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappconversation",
            index=models.Index(
                fields=["whatsapp_config", "status"],
                name="whatsapp_co_whatsap_3cd1b0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappconversation",
            index=models.Index(
                fields=["company", "phone_number"],
                name="whatsapp_co_company_3f6d75_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappconversation",
            index=models.Index(
                fields=["last_active_at"], name="whatsapp_co_last_ac_674ec6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(
                fields=["event_type", "processing_status"],
                name="webhook_eve_event_t_9678a4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(
                fields=["company", "created_at"], name="webhook_eve_company_2407cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(
                fields=["processing_status", "created_at"],
                name="webhook_eve_process_ed9569_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(
                fields=["is_test"], name="webhook_eve_is_test_d263fb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="messagetemplate",
            unique_together={("company", "name")},
        ),
    ]
