# Generated by Django 4.2.11 on 2025-09-26 22:31

import apps.chat.models.context_files
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0002_agentconfig_commontool_toolcategory_toolusagelog_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContextFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre descriptivo del archivo", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Descripción del contenido del archivo"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Archivo de contexto (JSON, TXT, DOCX, PDF)",
                        upload_to=apps.chat.models.context_files.context_file_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["json", "txt", "docx", "pdf"]
                            )
                        ],
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("json", "JSON"),
                            ("txt", "Text"),
                            ("docx", "Word Document"),
                            ("pdf", "PDF"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        help_text="Tamaño del archivo en bytes"
                    ),
                ),
                (
                    "extracted_content",
                    models.TextField(
                        blank=True,
                        help_text="Contenido extraído del archivo para usar como contexto",
                    ),
                ),
                (
                    "content_summary",
                    models.TextField(
                        blank=True, help_text="Resumen automático del contenido"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Subido"),
                            ("processing", "Procesando"),
                            ("processed", "Procesado"),
                            ("error", "Error"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                (
                    "processing_error",
                    models.TextField(
                        blank=True, help_text="Error durante el procesamiento"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Metadatos adicionales (páginas, palabras, etc.)",
                    ),
                ),
                (
                    "agent_config",
                    models.ForeignKey(
                        help_text="Agente al que pertenece este archivo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="context_files",
                        to="chat.agentconfig",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_context_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Archivo de Contexto",
                "verbose_name_plural": "Archivos de Contexto",
                "db_table": "chat_context_files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContextFileProcessingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        help_text="Acción realizada (upload, extract, summarize, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Iniciado"),
                            ("completed", "Completado"),
                            ("failed", "Fallido"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True, help_text="Detalles del procesamiento"
                    ),
                ),
                (
                    "execution_time",
                    models.DurationField(
                        blank=True, help_text="Tiempo de ejecución", null=True
                    ),
                ),
                (
                    "context_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_logs",
                        to="chat.contextfile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Procesamiento",
                "verbose_name_plural": "Logs de Procesamiento",
                "db_table": "chat_context_file_processing_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentContextAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Si este archivo está actualmente activo para el agente",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Prioridad del archivo (mayor número = mayor prioridad)",
                    ),
                ),
                (
                    "context_instructions",
                    models.TextField(
                        blank=True,
                        help_text="Instrucciones específicas sobre cómo usar este archivo como contexto",
                    ),
                ),
                (
                    "agent_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_context_assignments",
                        to="chat.agentconfig",
                    ),
                ),
                (
                    "context_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="chat.contextfile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación de Contexto",
                "verbose_name_plural": "Asignaciones de Contexto",
                "db_table": "chat_agent_context_assignments",
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="contextfile",
            index=models.Index(
                fields=["agent_config", "status"], name="chat_contex_agent_c_adf072_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contextfile",
            index=models.Index(
                fields=["file_type"], name="chat_contex_file_ty_56d8e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contextfile",
            index=models.Index(
                fields=["uploaded_by"], name="chat_contex_uploade_861fe5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentcontextassignment",
            index=models.Index(
                fields=["agent_config", "is_active"],
                name="chat_agent__agent_c_5c1a96_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agentcontextassignment",
            index=models.Index(
                fields=["priority"], name="chat_agent__priorit_4c0f14_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="agentcontextassignment",
            unique_together={("agent_config", "context_file")},
        ),
    ]
