# Generated by Django 4.2.11 on 2025-09-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_contextfile_contextfileprocessinglog_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentprompt",
            name="prompt_type",
            field=models.CharField(
                choices=[
                    ("instruction", "Instrucción"),
                    ("example", "Ejemplo"),
                    ("constraint", "Restricción"),
                    ("template", "Plantilla"),
                    ("fallback", "Respaldo"),
                    ("knowledge", "Conocimiento Específico"),
                ],
                max_length=20,
                verbose_name="Tipo de Prompt",
            ),
        ),
    ]
