# Generated by Django 4.2.11 on 2025-10-01 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0004_alter_agentprompt_prompt_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "agent_name",
                    models.CharField(
                        help_text="Nombre del agente asignado", max_length=100
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Título generado automáticamente basado en el primer mensaje",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activa"),
                            ("ended", "Finalizada"),
                            ("archived", "Archivada"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Metadata adicional como configuración del agente, contexto, etc.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_conversation",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ConversationMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "Usuario"),
                            ("assistant", "Asistente"),
                            ("system", "Sistema"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "agent_name",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del agente que generó la respuesta (para mensajes de assistant)",
                        max_length=100,
                    ),
                ),
                ("token_count", models.IntegerField(blank=True, null=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Metadata adicional como tiempo de respuesta, modelo usado, etc.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.conversation",
                    ),
                ),
            ],
            options={
                "db_table": "chat_conversation_message",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["conversation", "created_at"],
                        name="chat_conver_convers_0779d5_idx",
                    ),
                    models.Index(
                        fields=["role", "created_at"],
                        name="chat_conver_role_c4f2dd_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["user", "-updated_at"], name="chat_conver_user_id_e2a76b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["status", "-updated_at"], name="chat_conver_status_7eb480_idx"
            ),
        ),
    ]
